; PlatformIO project configuration for the Nano frequency detector firmware; it provides compiled/uploaded Arduino Nano firmware settings.

; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nano_every]
platform = atmelmegaavr
board = nano_every
framework = arduino
lib_deps =
	kosme/arduinoFFT @ ^2.0.4
